


parameters = {'SYS_INIT': [{'address':  0,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
                 'LOL_B': [{'address':  0,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
                 'LOL_A': [{'address':  0,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],

                   'LOS': [{'address':  0,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],

               'CLK0_EN': [{'address':  3,
                            'reg_MSB':  0,
                            'reg_LSB':  0}],
               'CLK1_EN': [{'address':  3,
                            'reg_MSB':  1,
                            'reg_LSB':  1}],
               'CLK2_EN': [{'address':  3,
                            'reg_MSB':  2,
                            'reg_LSB':  2}],
               'CLK3_EN': [{'address':  3,
                            'reg_MSB':  3,
                            'reg_LSB':  3}],
               'CLK4_EN': [{'address':  3,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
               'CLK5_EN': [{'address':  3,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'CLK6_EN': [{'address':  3,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'CLK7_EN': [{'address':  3,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],


              'OEB_MASK': [{'address':  9,
                            'reg_MSB':  7,
                            'reg_LSB':  0}],


             'CLKIN_DIV': [{'address': 15,
                            'reg_MSB':  7,
                            'reg_LSB':  6}],

              'PLLB_SRC': [{'address': 15,
                            'reg_MSB':  3,
                            'reg_LSB':  3}],
              'PLLA_SRC': [{'address': 15,
                            'reg_MSB':  2,
                            'reg_LSB':  2}],

              'CLK0_PDN': [{'address': 16,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK1_PDN': [{'address': 17,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK2_PDN': [{'address': 18,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK3_PDN': [{'address': 19,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK4_PDN': [{'address': 20,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK5_PDN': [{'address': 21,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK6_PDN': [{'address': 22,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK7_PDN': [{'address': 23,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],

               'MS0_INT': [{'address': 16,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS1_INT': [{'address': 17,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS2_INT': [{'address': 18,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS3_INT': [{'address': 19,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS4_INT': [{'address': 20,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS5_INT': [{'address': 21,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],

               'FBA_INT': [{'address': 22,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'FBB_INT': [{'address': 23,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],

               'MS0_SRC': [{'address': 16,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS1_SRC': [{'address': 17,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS2_SRC': [{'address': 18,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS3_SRC': [{'address': 19,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS4_SRC': [{'address': 20,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS5_SRC': [{'address': 21,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS6_SRC': [{'address': 22,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS7_SRC': [{'address': 23,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],

              'CLK0_INV': [{'address': 16,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK1_INV': [{'address': 17,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK2_INV': [{'address': 18,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK3_INV': [{'address': 19,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK4_INV': [{'address': 20,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK5_INV': [{'address': 21,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK6_INV': [{'address': 22,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK7_INV': [{'address': 23,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],

              'CLK0_SRC': [{'address': 16,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK1_SRC': [{'address': 17,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK2_SRC': [{'address': 18,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK3_SRC': [{'address': 19,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK4_SRC': [{'address': 20,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK5_SRC': [{'address': 21,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK6_SRC': [{'address': 22,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK7_SRC': [{'address': 23,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],

             'CLK0_IDRV': [{'address': 16,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK1_IDRV': [{'address': 17,
                            'reg_MSB':  0,
                            'reg_LSB':  2}],
             'CLK2_IDRV': [{'address': 18,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK3_IDRV': [{'address': 19,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK4_IDRV': [{'address': 20,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK5_IDRV': [{'address': 21,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK6_IDRV': [{'address': 22,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK7_IDRV': [{'address': 23,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],

        'CLK3_DIS_STATE': [{'address': 24,
                            'reg_MSB':  7,
                            'reg_LSB':  6}],
        'CLK2_DIS_STATE': [{'address': 24,
                            'reg_MSB':  5,
                            'reg_LSB':  4}],
        'CLK1_DIS_STATE': [{'address': 24,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
        'CLK0_DIS_STATE': [{'address': 24,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],

        'CLK7_DIS_STATE': [{'address': 25,
                            'reg_MSB':  7,
                            'reg_LSB':  6}],
        'CLK6_DIS_STATE': [{'address': 25,
                            'reg_MSB':  5,
                            'reg_LSB':  4}],
        'CLK5_DIS_STATE': [{'address': 25,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
        'CLK4_DIS_STATE': [{'address': 25,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],

# PLL Dividers A & B

               'MSNA_P1': [{'address': 28,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'address': 29,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 30,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNA_P2': [{'address': 31,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 32,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 33,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNA_P3': [{'address': 26,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 27,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0},
                           {'address': 31,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16}],

               'MSNB_P1': [{'address': 36,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'address': 37,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 38,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNB_P2': [{'address': 39,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 40,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 41,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNB_P3': [{'address': 34,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 35,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0},
                           {'address': 39,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16}],

# MultiSynth 0
                'R0_DIV': [{'address': 44,
                            'reg_MSB':  6,
                            'reg_LSB':  4,
                            'dat_MSB':  2,
                            'dat_LSB':  0}],

            'MS0_DIVBY4': [{'address': 44,
                            'reg_MSB':  3,
                            'reg_LSB':  2,
                            'dat_MSB':  1,
                            'dat_LSB':  0}],

                'MS0_P1': [{'address': 44,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'address': 45,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 46,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS0_P2': [{'address': 47,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 48,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 49,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS0_P3': [{'address': 42,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 43,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0},
                           {'address': 47,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16}],

# MultiSynth 1
                'R1_DIV': [{'address': 52,
                            'reg_MSB':  6,
                            'reg_LSB':  4,
                            'dat_MSB':  2,
                            'dat_LSB':  0}],

            'MS1_DIVBY4': [{'address': 52,
                            'reg_MSB':  3,
                            'reg_LSB':  2,
                            'dat_MSB':  1,
                            'dat_LSB':  0}],

                'MS1_P1': [{'address': 52,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'address': 53,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 54,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS1_P2': [{'address': 55,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 56,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 57,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS1_P3': [{'address': 55,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 50,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 51,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],

# MultiSynth 2
                'R2_DIV': [{'address': 60,
                            'reg_MSB':  6,
                            'reg_LSB':  4,
                            'dat_MSB':  2,
                            'dat_LSB':  0}],

            'MS2_DIVBY4': [{'address': 60,
                            'reg_MSB':  3,
                            'reg_LSB':  2,
                            'dat_MSB':  1,
                            'dat_LSB':  0}],

                'MS2_P1': [{'address': 60,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'address': 61,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 62,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS2_P2': [{'address': 63,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 64,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 65,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS2_P3': [{'address': 63,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'address': 58,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'address': 59,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],

# MultiSynth 3 - 7 are TBD


# Spread Spectrum, just enough control so I can disable it

                'SSC_EN': [{'address': 149,
                            'reg_MSB':   7,
                            'reg_LSB':   7}],


# VCXO, I don't care about this feature


# Phase offsets

            'CLK0_PHOFF': [{'address': 165,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK1_PHOFF': [{'address': 166,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK2_PHOFF': [{'address': 167,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK3_PHOFF': [{'address': 168,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK4_PHOFF': [{'address': 169,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK5_PHOFF': [{'address': 170,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],


# Miscelaneous stuff

              'PLLA_RST': [{'address': 177,
                            'reg_MSB':   5,
                            'reg_LSB':   5}],

              'PLLB_RST': [{'address': 177,
                            'reg_MSB':   7,
                            'reg_LSB':   7}],

               'XTAL_CL': [{'address': 183,
                            'reg_MSB':   7,
                            'reg_LSB':   6}],

       'CLKIN_FANOUT_EN': [{'address': 187,
                            'reg_MSB':   7,
                            'reg_LSB':   7}],

          'XO_FANOUT_EN': [{'address': 187,
                            'reg_MSB':   6,
                            'reg_LSB':   6}],

          'MS_FANOUT_EN': [{'address': 187,
                            'reg_MSB':   4,
                            'reg_LSB':   4}],


             }
