
name = 'Si5351'
address = 0x60

parameters = {'SYS_INIT': [{'register': 0,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
                 'LOL_B': [{'register': 0,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
                 'LOL_A': [{'register': 0,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],

                   'LOS': [{'register': 0,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],

         'SYS_INIT_MASK': [{'register': 2,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
            'LOL_B_MASK': [{'register': 2,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
            'LOL_A_MASK': [{'register': 2,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
              'LOS_MASK': [{'register': 2,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],

              'CLK0_OEB': [{'register': 3,
                            'reg_MSB':  0,
                            'reg_LSB':  0}],
              'CLK1_OEB': [{'register': 3,
                            'reg_MSB':  1,
                            'reg_LSB':  1}],
              'CLK2_OEB': [{'register': 3,
                            'reg_MSB':  2,
                            'reg_LSB':  2}],
              'CLK3_OEB': [{'register': 3,
                            'reg_MSB':  3,
                            'reg_LSB':  3}],
              'CLK4_OEB': [{'register': 3,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK5_OEB': [{'register': 3,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
              'CLK6_OEB': [{'register': 3,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
              'CLK7_OEB': [{'register': 3,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],


              'OEB_MASK': [{'register': 9,
                            'reg_MSB':  7,
                            'reg_LSB':  0}],


             'CLKIN_DIV': [{'register':15,
                            'reg_MSB':  7,
                            'reg_LSB':  6}],

              'PLLB_SRC': [{'register':15,
                            'reg_MSB':  3,
                            'reg_LSB':  3}],
              'PLLA_SRC': [{'register':15,
                            'reg_MSB':  2,
                            'reg_LSB':  2}],

              'CLK0_PDN': [{'register':16,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK1_PDN': [{'register':17,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK2_PDN': [{'register':18,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK3_PDN': [{'register':19,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK4_PDN': [{'register':20,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK5_PDN': [{'register':21,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK6_PDN': [{'register':22,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],
              'CLK7_PDN': [{'register':23,
                            'reg_MSB':  7,
                            'reg_LSB':  7}],

               'MS0_INT': [{'register':16,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS1_INT': [{'register':17,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS2_INT': [{'register':18,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS3_INT': [{'register':19,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS4_INT': [{'register':20,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'MS5_INT': [{'register':21,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],

               'FBA_INT': [{'register':22,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],
               'FBB_INT': [{'register':23,
                            'reg_MSB':  6,
                            'reg_LSB':  6}],

               'MS0_SRC': [{'register':16,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS1_SRC': [{'register':17,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS2_SRC': [{'register':18,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS3_SRC': [{'register':19,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS4_SRC': [{'register':20,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS5_SRC': [{'register':21,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS6_SRC': [{'register':22,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],
               'MS7_SRC': [{'register':23,
                            'reg_MSB':  5,
                            'reg_LSB':  5}],

              'CLK0_INV': [{'register':16,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK1_INV': [{'register':17,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK2_INV': [{'register':18,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK3_INV': [{'register':19,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK4_INV': [{'register':20,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK5_INV': [{'register':21,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK6_INV': [{'register':22,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],
              'CLK7_INV': [{'register':23,
                            'reg_MSB':  4,
                            'reg_LSB':  4}],

              'CLK0_SRC': [{'register':16,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK1_SRC': [{'register':17,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK2_SRC': [{'register':18,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK3_SRC': [{'register':19,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK4_SRC': [{'register':20,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK5_SRC': [{'register':21,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK6_SRC': [{'register':22,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
              'CLK7_SRC': [{'register':23,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],

             'CLK0_IDRV': [{'register':16,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK1_IDRV': [{'register':17,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK2_IDRV': [{'register':18,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK3_IDRV': [{'register':19,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK4_IDRV': [{'register':20,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK5_IDRV': [{'register':21,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK6_IDRV': [{'register':22,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],
             'CLK7_IDRV': [{'register':23,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],

        'CLK3_DIS_STATE': [{'register':24,
                            'reg_MSB':  7,
                            'reg_LSB':  6}],
        'CLK2_DIS_STATE': [{'register':24,
                            'reg_MSB':  5,
                            'reg_LSB':  4}],
        'CLK1_DIS_STATE': [{'register':24,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
        'CLK0_DIS_STATE': [{'register':24,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],

        'CLK7_DIS_STATE': [{'register':25,
                            'reg_MSB':  7,
                            'reg_LSB':  6}],
        'CLK6_DIS_STATE': [{'register':25,
                            'reg_MSB':  5,
                            'reg_LSB':  4}],
        'CLK5_DIS_STATE': [{'register':25,
                            'reg_MSB':  3,
                            'reg_LSB':  2}],
        'CLK4_DIS_STATE': [{'register':25,
                            'reg_MSB':  1,
                            'reg_LSB':  0}],

# PLL Dividers A & B
               'MSNA_P1': [{'register':28,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'register':29,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':30,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNA_P2': [{'register':31,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':32,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':33,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNA_P3': [{'register':26,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':27,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0},
                           {'register':31,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16}],

               'MSNB_P1': [{'register':36,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'register':37,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':38,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNB_P2': [{'register':39,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':40,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':41,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
               'MSNB_P3': [{'register':34,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':35,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0},
                           {'register':39,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16}],

# MultiSynth 0
                'R0_DIV': [{'register':44,
                            'reg_MSB':  6,
                            'reg_LSB':  4,
                            'dat_MSB':  2,
                            'dat_LSB':  0}],

            'MS0_DIVBY4': [{'register':44,
                            'reg_MSB':  3,
                            'reg_LSB':  2,
                            'dat_MSB':  1,
                            'dat_LSB':  0}],

                'MS0_P1': [{'register':44,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'register':45,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':46,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS0_P2': [{'register':47,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':48,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':49,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS0_P3': [{'register':42,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':43,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0},
                           {'register':47,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16}],

# MultiSynth 1
                'R1_DIV': [{'register':52,
                            'reg_MSB':  6,
                            'reg_LSB':  4,
                            'dat_MSB':  2,
                            'dat_LSB':  0}],

            'MS1_DIVBY4': [{'register':52,
                            'reg_MSB':  3,
                            'reg_LSB':  2,
                            'dat_MSB':  1,
                            'dat_LSB':  0}],

                'MS1_P1': [{'register':52,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'register':53,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':54,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS1_P2': [{'register':55,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':56,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':57,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS1_P3': [{'register':55,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':50,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':51,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],

# MultiSynth 2
                'R2_DIV': [{'register':60,
                            'reg_MSB':  6,
                            'reg_LSB':  4,
                            'dat_MSB':  2,
                            'dat_LSB':  0}],

            'MS2_DIVBY4': [{'register':60,
                            'reg_MSB':  3,
                            'reg_LSB':  2,
                            'dat_MSB':  1,
                            'dat_LSB':  0}],

                'MS2_P1': [{'register':60,
                            'reg_MSB':  1,
                            'reg_LSB':  0,
                            'dat_MSB': 17,
                            'dat_LSB': 16},
                           {'register':61,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':62,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS2_P2': [{'register':63,
                            'reg_MSB':  3,
                            'reg_LSB':  0,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':64,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':65,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],
                'MS2_P3': [{'register':63,
                            'reg_MSB':  7,
                            'reg_LSB':  4,
                            'dat_MSB': 19,
                            'dat_LSB': 16},
                           {'register':58,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB': 15,
                            'dat_LSB':  8},
                           {'register':59,
                            'reg_MSB':  7,
                            'reg_LSB':  0,
                            'dat_MSB':  7,
                            'dat_LSB':  0}],

# MultiSynth 3

# MultiSynth 4

# MultiSynth 5

# MultiSynth 6

# MultiSynth 7



# Spread Spectrum, just enough control so I can disable it
                'SSC_EN': [{'register':149,
                            'reg_MSB':   7,
                            'reg_LSB':   7}],


# VCXO, I don't care about this feature


# Phase offsets
            'CLK0_PHOFF': [{'register':165,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK1_PHOFF': [{'register':166,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK2_PHOFF': [{'register':167,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK3_PHOFF': [{'register':168,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK4_PHOFF': [{'register':169,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],
            'CLK5_PHOFF': [{'register':170,
                            'reg_MSB':   6,
                            'reg_LSB':   0}],


# Miscelaneous
              'PLLA_RST': [{'register':177,
                            'reg_MSB':   5,
                            'reg_LSB':   5}],
              'PLLB_RST': [{'register':177,
                            'reg_MSB':   7,
                            'reg_LSB':   7}],

               'XTAL_CL': [{'register':183,
                            'reg_MSB':   7,
                            'reg_LSB':   6}],

       'CLKIN_FANOUT_EN': [{'register':187,
                            'reg_MSB':   7,
                            'reg_LSB':   7}],
          'XO_FANOUT_EN': [{'register':187,
                            'reg_MSB':   6,
                            'reg_LSB':   6}],
          'MS_FANOUT_EN': [{'register':187,
                            'reg_MSB':   4,
                            'reg_LSB':   4}],
             }
